### ISSUE TITLE
Send via LNURL?

### ISSUE THREAD

**Issue by eliaspfeffer** [conduition/wos#1]
Trying to figure out, if you can directly send sats from your wallet via API_Token and API_Secret and only the receiver username - e.g. username@walletofsatoshi.com

Is that possible? Or DO I have to create an invoice all the time? Could you please give me an example how to implement it? 
Thanks! :)

**Comment by conduition** [comment]
This shouldn't be too hard to add. One sec

**Comment by conduition** [comment]
Fixed :) See 73f3eda

**Comment by eliaspfeffer** [comment]
Freaking legend! Awesome, thanks, will try it out! :)))
